version: '3.8'
services:
  api:
    build: 
      context: ./Recollect.Api
      dockerfile: Dockerfile.dockerfile
    # Use host network for Tailscale access (remove ports & networks when using host)
    network_mode: "host"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:7001
      - ConnectionStrings__DefaultConnection=Host=127.0.0.1;Database=Recollect;Username=postgres;Password=secret
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: Recollect
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    # Keep db on bridge network
    networks:
      - recollect-network

volumes:
  postgres_data:

networks:
  recollect-network:
    driver: bridge
