version: '3.8'
services:
  api:
    build: 
      context: ./Recollect.Api
      dockerfile: Dockerfile.dockerfile
    ports:
      - "7001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=db;Database=Recollect;Username=postgres;Password=secret
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - recollect-network
    # Use host network for Tailscale access
    network_mode: "host"
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: Recollect
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - recollect-network

volumes:
  postgres_data:

networks:
  recollect-network:
    driver: bridge
